export const cities = [
  { name: "Gaza", translationKey: "gaza" },
  { name: "Jerusalem", translationKey: "jerusalem" },
  { name: "Beersheba", translationKey: "beersheba" },
  { name: "Bethlehem", translationKey: "bethlehem" },
  { name: "Hebron", translationKey: "hebron" },
  { name: "Al Ramla", translationKey: "al_ramla" },
  { name: "Ramallah", translationKey: "ramallah" },
  { name: "Jaffa", translationKey: "jaffa" },
  { name: "Nablus", translationKey: "nablus" },
  { name: "Tulkarm", translationKey: "tulkarm" },
  { name: "Jinin", translationKey: "jinin" },
  { name: "Baysan", translationKey: "baysan" },
  { name: "Nazareth", translationKey: "nazareth" },
  { name: "Haifa", translationKey: "haifa" },
  { name: "Tiberias", translationKey: "tiberias" },
  { name: "Safad", translationKey: "safad" },
  { name: "Akre", translationKey: "akre" },
];
