export const cities = [
  { name: "Gaza" },
  { name: "Al-Quds" },
  { name: "Beersheba" },
  { name: "Bethlehem" },
  { name: "Al-Khalil" },
  { name: "Al Ramla" },
  { name: "Ramallah" },
  { name: "Yaffa" },
  { name: "Nablus" },
  { name: "Tulkarm" },
  { name: "Jinin" },
  { name: "Baysan" },
  { name: "Nazareth" },
  { name: "Haifa" },
  { name: "Tiberias" },
  { name: "Safad" },
  { name: "Akka" },
];
