export const cities = [
  { name: "Gaza" },
  { name: "Jerusalem" },
  { name: "Beersheba" },
  { name: "Bethlehem" },
  { name: "Hebron" },
  { name: "Al Ramla" },
  { name: "Ramallah" },
  { name: "Jaffa" },
  { name: "Nablus" },
  { name: "Tulkarm" },
  { name: "Jinin" },
  { name: "Baysan" },
  { name: "Nazareth" },
  { name: "Haifa" },
  { name: "Tiberias" },
  { name: "Safad" },
  { name: "Akre" },
];
